#!/usr/bin/env bash

# Install Nginx
sudo apt-get update -y -qq && \
sudo apt-get install nginx -y

# Configure Nginx to include custom HTTP response header
sudo bash -c 'cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        root /var/www/html;
        index index.html index.htm;
        add_header X-Served-By $HOSTNAME;
    }
}
EOF'

# Restart Nginx
sudo systemctl restart nginx

# Check if the custom header is added
response=$(curl -sI localhost | grep X-Served-By)
echo "[Got]"
echo "$response"
echo "[Expected]"
echo "#"

