#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5819-webs
    bind *:80
    mode http
    balance roundrobin
    server 6056-web-01 3.80.81.172:80 check
    server 6056-web-02 54.242.70.85:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
