#!/usr/bin/env bash

# Update package repositories
sudo apt-get update -y

# Install Nginx
sudo apt-get install -y nginx

# Nginx configuration
config="server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
            try_files \$uri \$uri/ =404;
        }
        location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}"

# Change ownership of index.html file
sudo chown "$USER":"$USER" /var/www/html/index.html

# Update default Nginx site configuration
echo "$config" | sudo tee /etc/nginx/sites-available/default >/dev/null

# Restart Nginx service
sudo service nginx restart

